<a href="https://colab.research.google.com/github/Punamkoli14/Task1_Data_Cleaning/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("/content/sales_data.csv.zip")

In [4]:
data.head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418

In [5]:
data.sample(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
79235,2015-12-08,8,December,2015,35,Adults (35-64),M,Canada,British Columbia,Accessories,Tires and Tubes,Mountain Tire Tube,30,2,5,89,60,149
23529,2015-12-10,10,December,2015,34,Young Adults (25-34),M,Australia,Victoria,Accessories,Fenders,Fender Set - Mountain,21,8,22,197,168,365
42380,2013-12-19,19,December,2013,44,Adults (35-64),F,United Kingdom,England,Accessories,Hydration Packs,Hydration Pack - 70 oz.,14,21,55,445,294,739
83762,2014-06-17,17,June,2014,49,Adults (35-64),M,United States,California,Accessories,Tires and Tubes,Patch Kit/8 Patches,2,1,2,2,2,4
70485,2011-09-10,10,September,2011,52,Adults (35-64),F,United States,California,Bikes,Road Bikes,"Road-150 Red, 48",1,2171,3578,1335,2171,3506

In [6]:
data.shape

(113036, 18)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [8]:
data.describe()

,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000,113036.000000
mean,15.665753,2014.401739,35.919212,11.901660,267.296366,452.938427,285.051665,469.318695,754.370360
std,8.781567,1.272510,11.021936,9.561857,549.835483,922.071219,453.887443,884.866118,1309.094674
min,1.000000,2011.000000,17.000000,1.000000,1.000000,2.000000,-30.000000,1.000000,2.000000
25%,8.000000,2013.000000,28.000000,2.000000,2.000000,5.000000,29.000000,28.000000,63.000000
50%,16.000000,2014.000000,35.000000,10.000000,9.000000,24.000000,101.000000,108.000000,223.000000
75%,23.000000,2016.000000,43.000000,20.000000,42.000000,70.000000,358.000000,432.000000,800.000000
max,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,15096.000000,42978.000000,58074.000000

In [9]:
data.columns

Index(['Date', 'Day', 'Month', 'Year', 'Customer_Age', 'Age_Group',
       'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product', 'Order_Quantity', 'Unit_Cost', 'Unit_Price',
       'Profit', 'Cost', 'Revenue'],
      dtype='object')

In [10]:
missing_values=data.isnull().sum()

In [11]:
missing_values

Date                0
Day                 0
Month               0
Year                0
Customer_Age        0
Age_Group           0
Customer_Gender     0
Country             0
State               0
Product_Category    0
Sub_Category        0
Product             0
Order_Quantity      0
Unit_Cost           0
Unit_Price          0
Profit              0
Cost                0
Revenue             0
dtype: int64

In [12]:
data.duplicated().value_counts()

False    112036
True       1000
Name: count, dtype: int64

In [13]:
data_new= data.drop_duplicates()

In [14]:
data_new

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,2014-04-02,2,April,2014,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,2016-04-02,2,April,2016,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207

In [15]:
data_types = data_new.dtypes

In [16]:
data_types

Date                object
Day                  int64
Month               object
Year                 int64
Customer_Age         int64
Age_Group           object
Customer_Gender     object
Country             object
State               object
Product_Category    object
Sub_Category        object
Product             object
Order_Quantity       int64
Unit_Cost            int64
Unit_Price           int64
Profit               int64
Cost                 int64
Revenue              int64
dtype: object

In [17]:
data_new.columns = data_new.columns.str.strip().str.lower().str.replace(' ', '_')
data_new['country'] = data_new['country'].str.strip().str.title()

<ipython-input-17-d8a2c7b48d7d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_new['country'] = data_new['country'].str.strip().str.title()

In [18]:
{
    "Missing Values": missing_values,
    "Data Types": data_types,
    "Shape Before Cleaning": data.shape,
    "Shape After Removing Duplicates": data_new.shape,
    "Cleaned Column Names": data_new.columns.tolist()
}

{'Missing Values': Date                0
 Day                 0
 Month               0
 Year                0
 Customer_Age        0
 Age_Group           0
 Customer_Gender     0
 Country             0
 State               0
 Product_Category    0
 Sub_Category        0
 Product             0
 Order_Quantity      0
 Unit_Cost           0
 Unit_Price          0
 Profit              0
 Cost                0
 Revenue             0
 dtype: int64,
 'Data Types': Date                object
 Day                  int64
 Month               object
 Year                 int64
 Customer_Age         int64
 Age_Group           object
 Customer_Gender     object
 Country             object
 State               object
 Product_Category    object
 Sub_Category        object
 Product             object
 Order_Quantity       int64
 Unit_Cost            int64
 Unit_Price           int64
 Profit               int64
 Cost                 int64
 Revenue              int64
 dtype: object,
 'Shape Before Cleaning': (113036, 18),
 'Shape After Removing Duplicates': (112036, 18),
 'Cleaned Column Names': ['date',
  'day',
  'month',
  'year',
  'customer_age',
  'age_group',
  'customer_gender',
  'country',
  'state',
  'product_category',
  'sub_category',
  'product',
  'order_quantity',
  'unit_cost',
  'unit_price',
  'profit',
  'cost',
  'revenue']}

In [22]:
data_new = data_new.copy()
data_new['date'] = pd.to_datetime(data_new['date'], errors='coerce')
data_new['date'] = data_new['date'].dt.strftime('%d-%m-%Y')

In [23]:
type(data_new.date[0])

str

In [24]:
data_new.date[0]

'26-11-2013'